In [2]:
import numpy as np


In [4]:
import csv

In [6]:
with open('/home/AIML_Student/Documents/abc.csv','rt') as f:
    data=csv.reader(f)
    for row in data:
        print(row)
    

['monday', 'tuesday', 'wednesday']
['thursday', 'friday', 'saturday']


In [11]:
with open('/home/AIML_Student/Documents/abc.csv','w') as file:
    writer=csv.writer(file,delimiter=',',quotechar=" ",quoting=csv.QUOTE_MINIMAL)
    writer.writerow(['monday','tueday','wednesday'])

In [12]:
with open('/home/AIML_Student/Documents/abc.csv','rt') as f:
    data=csv.reader(f)
    for row in data:
        print(row)

['monday', 'tueday', 'wednesday']


In [37]:
 a=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
b=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
for i in b:
    if i%2!=0:
        b[i]=-1

In [41]:
b

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [51]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
z=np.array([])
w=np.array([])

In [54]:
for i in range(10):
    if x[i]>y[i]:
        z=np.append(z,i)

In [55]:
z

array([1., 2., 4., 5., 6., 7., 8., 9.])

In [57]:
for i in range(10):
    if x[i]==y[i]:
        w=np.append(w,i)

In [58]:
w

array([0.])

In [59]:
p=np.arange(100).reshape(5,-1)

In [60]:
p

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [66]:
for j in range(4):
    print(p[:,j])
        
        

[ 0 20 40 60 80]
[ 1 21 41 61 81]
[ 2 22 42 62 82]
[ 3 23 43 63 83]
